name: Rolling Boiler
favicon: null
layout_spectrum: 0.6354757735971361
typography_spectrum: 0.9742960561998188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.35898430459201336
  lightness: 0.881611306220293
  saturation: 0.705817753681913
  rhythmicContrast: 0.5219392653089017
purpose: []
